spring:
  application:
    name: announcement-service
  datasource:
    url: jdbc:postgresql://localhost:5432/announcement_service
    username: announcement_service
    password: 1234
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      indent-output: true
      fail-on-empty-beans: false
jwt:
  secret: ${JWT_SECRET:secret}
  access-token:
    ttl: 1000000

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp